name: Book-Archiving CD

on:
  workflow_dispatch:

  pull_request:
    branches:
      - develop
      - main
    types: [ closed ]

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.SUBMODULE_ACCESS_TOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --stacktrace

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/bookpin:latest . --push

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.WAS_HOST }}
          username: ${{ secrets.WAS_USERNAME }}
          key: ${{ secrets.WAS_SSH_KEY }}
          port: ${{ secrets.WAS_SSH_PORT }}
          script: |
            sudo sh zero-down-time.sh

      - name: Send Deploy Success Notification
        if: ${{ success() }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: "Book-Archiving 배포 성공"
          description: |
            **PR:** #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}
            **Author:** ${{ github.event.pull_request.user.login }}
            **Branch:** `${{ github.head_ref }}` → `${{ github.base_ref }}`
          color: 0x00FF00
          url: ${{ github.event.pull_request.html_url }}

      - name: Send Deploy Failure Notification
        if: ${{ failure() }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: "Book-Archiving 배포 실패"
          description: |
            **PR:** #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}
            **Author:** ${{ github.event.pull_request.user.login }}
            **Branch:** `${{ github.head_ref }}` → `${{ github.base_ref }}`
          color: 0xFF0000
          url: ${{ github.event.pull_request.html_url }}
